### ISSUE TITLE
Creating more than one dropzone component doesn't seem to work

### ISSUE THREAD

**Issue by bj-mcduck** [FutoRicky/ember-cli-dropzonejs#11]
I've got multiple dropzones I'd like for one page. The first one is working correctly, but adding others only initiates the first one.

```
DEBUG: -------------------------------
ember.debug.js:5378DEBUG: Ember                    : 1.13.7
ember.debug.js:5378DEBUG: Ember Data               : 1.13.8
ember.debug.js:5378DEBUG: jQuery                   : 1.11.3
ember.debug.js:5378DEBUG: Ember Simple Auth        : 0.8.0
ember.debug.js:5378DEBUG: Ember Simple Auth Devise : 0.8.0
ember.debug.js:5378DEBUG: -------------------------------
```

**Comment by bj-mcduck** [comment]
<img width="832" alt="screen shot 2015-09-18 at 12 25 39 pm" src="https://cloud.githubusercontent.com/assets/1518678/9968930/665dae16-5e00-11e5-8e16-e8b40a03b4c5.png">

**Comment by FutoRicky** [comment]
Fixed. https://github.com/FutoRicky/ember-cli-dropzonejs/commit/1479bfda7d29c0069fba5c1775a10b044e4f58c5

**Comment by bj-mcduck** [comment]
Cool! Thanks!
