### ISSUE TITLE
success callback context

### ISSUE THREAD

**Issue by pixelig** [FutoRicky/ember-cli-dropzonejs#12]
Hi,

i want to trigger an action via the success callback, so i in my component i did the following:

`{{drop-zone url="http://localhost/upload" success=uploadSuccess}}`

The 'uploadSuccess` function gets called as expected, but loses the context of my wrapping component. Is there anyway to access my component / ember app?

**Comment by FutoRicky** [comment]
Can you provide an example?

**Comment by pixelig** [comment]
Something like this:

```
UploadFieldComponent = Ember.Component.extend({
  uploadSuccess: function(file, response) {
    console.log('this', this);
    console.log('file', file);
    console.log('response', response);
  }
});
```

and in the template the line from above:
`{{drop-zone url="http://localhost/upload" success=uploadSuccess}}`

When i upload a file the `file` and `response` objects are what i expected, but `this` refers to the dropzone-js context, which also makes sense, since the `uploadSuccess` function is just passed through to dropzone-js. Is there any way to access the `response` object in my Ember Component? My API Server sends an Image ID after processing the upload, which i'd like to use in my Ember App.

Thanks in advance.

**Comment by FutoRicky** [comment]
Try doing the function like so:

```
UploadFieldComponent = Ember.Component.extend({
  uploadSuccess: Ember.run(this, function(file, response) {
    console.log('this', this);
    console.log('file', file);
    console.log('response', response);
  })
});
```

This is an ember thing, the addon has nothing to do with it.

**Comment by wayne-o** [comment]
When I do this - the `uploadSuccess` function is called once when the page loads and that's it? It never gets called again? How can I do this?

**Comment by wayne-o** [comment]
If i add another callback for something like `fileadded` that isn't using ember.run this works  - seems like there could be a bug?
