### ISSUE TITLE
Is it possible to bind an action with the uploader?

### ISSUE THREAD

**Issue by chaitanyya** [FutoRicky/ember-cli-dropzonejs#14]
I want to perform an action whenever a file is added. Is it possible to do so? The action is in a controller.

**Comment by FutoRicky** [comment]
Yes, you can use the `addedfile` event. Take the function you have in the action, and define it as a function object and assign it to the addedfile event in the component.

Example:
`{{drop-zone url='/' addedfile=yourEvent}}`
`yourEvent` is defined in your controller.

For more info, http://www.dropzonejs.com/#event
