### ISSUE TITLE
`dropzoneOptions` validation checking is too reckless

### ISSUE THREAD

**Issue by nightire** [FutoRicky/ember-cli-dropzonejs#15]
https://github.com/FutoRicky/ember-cli-dropzonejs/blob/master/addon/components/drop-zone.js#L216

Here, some options are nullable, for example, `thumbnailHeight` and `thumbnailWidth`, they should be pass in this checker even set to `null`.

References:

http://www.dropzonejs.com/#config-thumbnailHeight
http://www.dropzonejs.com/#config-thumbnailWidth

**Comment by FutoRicky** [comment]
Thank you for this! Will work on this as soon as I get some free time.

**Comment by FutoRicky** [comment]
Changed logic to accept `null` value for thumbnailHeight and thumbnailWidth https://github.com/FutoRicky/ember-cli-dropzonejs/commit/79490bcff2308a9ceabad0a801a382b5988c3d54
