### ISSUE TITLE
Error in tooltip

### ISSUE THREAD

**Issue by yankeeinlondon** [FutoRicky/ember-cli-dropzonejs#17]
I was playing with the demo and noticed that whatever file I uploaded I would get an ugly error message from the hover-event tooltip. See visual below.

![image](https://cloud.githubusercontent.com/assets/980757/11015915/c6df65ba-8568-11e5-947a-684fd63051ea.png)

**Comment by FutoRicky** [comment]
This is because there is no endpoint specified. I should clean that for the demo though, thanks.

**Comment by yankeeinlondon** [comment]
Yeah I forked and spent a lot of time with this plugin. I'd suggest, if nothing else, just put '#' as the url and the error goes away. Gives a much more positive view of the component.

**Comment by yankeeinlondon** [comment]
I was going to send you a PR as you got this ball rolling but by the time I was done it was drastically changed and I need it for some work i'm doing right now so I figured better just to make it it's own thing. Thanks for the inspiration though.

Here's my component if you're interested: https://ui-dropzone.firebaseapp.com/

Anyway, I'll close this issue for now.

**Comment by FutoRicky** [comment]
![](http://media1.giphy.com/media/vMnuZGHJfFSTe/giphy.gif)
