### ISSUE TITLE
How to attach all the dropzone options 

### ISSUE THREAD

**Issue by nagkumar** [FutoRicky/ember-cli-dropzonejs#20]
How to attach all the options associated with a dropzone in hbs file.. such as all the events fired by dropzone  etc... In j's we use .options.I'd to assign the handlers.. not sure how same is done in ember as it needs to do things in routes controllet's etc...

**Comment by nagkumar** [comment]
Register for events

If you want to register to some event you can do so on the dropzone object itself:

```
Dropzone.options.myDropzone({ 
  init: function() { 
    this.on("error", function(file, message) { alert(message); }); 
  } 
}); 
// or if you need to access a Dropzone somewhere else: 
var myDropzone = Dropzone.forElement("div#my-dropzone"); 
myDropzone.on("error", function(file, message) { 
  alert(message); 
});
```

For a list of all events, please look at the chapter»Events« in the documentation or at the sourcenter...
https://github.com/enyo/dropzone/blob/master/README.md

**Comment by nagkumar** [comment]
It is also related to how to use emberdropzone  behave differently for different pages or same page having multiple dropzone areas

**Comment by FutoRicky** [comment]
This is fairly easy. Just call the component and assign your error event to the `error` property.

Example:

`{{drop-zone url='http://example.com' error=yourErrorEvent}}`

Docs about error event: http://www.dropzonejs.com/#event-error
