### ISSUE TITLE
Support for `Closure Action`

### ISSUE THREAD

**Issue by vsymguysung** [FutoRicky/ember-cli-dropzonejs#24]
Any plan to support `Closure Action` as we're moving fast toward Ember 2.0 ? It will allow us to avoid using a `Controller` for event handling. BTW, Thanks much for your work.

**Comment by FutoRicky** [comment]
9e327fdf9698d7c2c9a2bbccb92205ec3635448f
Upgraded the addon to ember-cli `v2.8.0` so it should be supported now. Feel free to open the issue if it's not. Sorry for the delay in this.
