### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by arunrajasankar** [FutoRicky/ember-cli-dropzonejs#27]
I get this error

Uncaught Error: Assertion Failed: A helper named 'drop-zone' could not be found

 even after following these steps

> ember install ember-cli-dropzonejs
> bower install dropzone

`var app = new EmberApp({

---

  emberCliDropzonejs: {
    includeDropzoneCss: false
  }

---

});`

```
addedFileEvent: Ember.computed(function() {
    return function() {
      // do something...
    };
  }),

```

{{drop-zone url='http://example.com/example' addfile=addedFileEvent}}

**Comment by IAmJulianAcosta** [comment]
Try to update ember-cli, I had the same problem but solved now

**Comment by FutoRicky** [comment]
@arunrajasankar Did @IAmJulianAcosta's advice solve your issue?
