### ISSUE TITLE
Unable to use this reference in event handlers

### ISSUE THREAD

**Issue by ezequielo** [FutoRicky/ember-cli-dropzonejs#33]
### Description

When extending the component or creating a event handler as said in the documentation, it works fine but `this`is a reference to a DropZone objects, not a controller. Therefore, you cannot perform actions like `this.transitionTo()` or `this.get()`.
### Example

```
// template.hbs
 {{drop-zone url='<some_url>' success=successEvent}}
```

Here I use it in a route but the effect is the same as extending the component:

```
// route controller.js
export default Ember.Controller.extend({
    successEvent: function(){
        this.transitionTo('<success_route>') // this fails since this is not a component
    },
});
```

Maybe I am not using it correctly. I have tried to do it as described in READ.me file but I get `Uncaught TypeError: Cannot read property 'apply' of undefined` error

**Comment by jcbvm** [comment]
To keep the scope of your controller so that you can call 'this' in the event handler, instead of directly passing your event function, use the scoped action helper from Ember:

```
// template.hbs
{{drop-zone url='<some_url>' success=(action 'successEvent')}}
```

This will wrap the event handler in another function which will keep the scope to your controller.
Your successEvent should now move to the 'actions' hash in your controller.

@ezequielo Maybe this should be properly documented

**Comment by jevanlingen** [comment]
In addition to @jcbvm's comment, if you need both controller and dropzone objects, you can use the `Dropzone.forElement` function.

E.G.

``` hbs
//template.hbs
{{drop-zone id='my-drop-zone' url='<some_url>' success=(action 'successEvent')}}
```

``` javascript
import Ember from 'ember';

export default Ember.Controller.extend({
    actions: {
        successEvent() {
            const dropzoneObj = Dropzone.forElement('#my-drop-zone');

            //dropzoneObj.doDropzoneAction();
            //this.doControllerAction();
        }
    }
});
```
