### ISSUE TITLE
Fix for flickering breaking on 'dragenter'

### ISSUE THREAD

**Issue by radcliff** [FutoRicky/ember-cli-dropzonejs#42]
Hey, I noticed that the recent fix for flickering is breaking for me when I drag a file into the dropzone element. I am getting:

`Uncaught TypeError: Cannot read property 'classList' of undefined`

which is referencing this code:

```
getDropzoneOptions: function getDropzoneOptions() {
      var onDragEnterLeaveHandler = function onDragEnterLeaveHandler(dropzoneInstance) {
        var onDrag = (function (element) {
          var dragCounter = 0;

          return {
            enter: function enter(event) {
              event.preventDefault();
              dragCounter++;
              element.classList.add('dz-drag-hover');
            },
            leave: function leave() {
              dragCounter--;

              if (dragCounter === 0) {
                element.classList.remove('dz-drag-hover');
              }
            }
          };
        }).call(dropzoneInstance.element);

        dropzoneInstance.on('dragenter', onDrag.enter);
        dropzoneInstance.on('dragleave', onDrag.leave);
      };
```

re: https://github.com/FutoRicky/ember-cli-dropzonejs/pull/35

Inside of the `enter` function, `element` is undefined, so `.classList` breaks here. 

Any help would be greatly appreciated. Thanks!

**Comment by radcliff** [comment]
since I don't fully understand what this function is doing, and it doesn't seem to be preventing the image upload behavior that I want, I hacked around the error in the interim with this:

```
return {
          enter(event) {
            event.preventDefault();
            dragCounter++;
            try { element.classList.add('dz-drag-hover'); } catch(e) {};
          },
          leave() {
            dragCounter--;

            if (dragCounter === 0) {
              try { element.classList.remove('dz-drag-hover'); } catch(e) {};
            }
          }
        };
```

I know this is ugly, but it helps me move on from this while I wait for the understanding.

**Comment by FutoRicky** [comment]
Fixed https://github.com/FutoRicky/ember-cli-dropzonejs/commit/b177e1d1eb158fb12df148b0f351658360494a60

Thanks to @bradleypriest
(mistyped commit message)

**Comment by radcliff** [comment]
thank you!
