### ISSUE TITLE
Fix deprecation message

### ISSUE THREAD

**Issue by alltouch** [FutoRicky/ember-cli-dropzonejs#44]
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`

more info here https://github.com/ember-cli/ember-cli-htmlbars/issues/77

**Comment by FutoRicky** [comment]
Updated `ember-cli-htmlbars` to `v1.1.0` 

https://github.com/FutoRicky/ember-cli-dropzonejs/commit/62d3a8445660d9fb0e64ecc226e82f425ad753b4

**Comment by alltouch** [comment]
@FutoRicky, thanks for quick fix
