### ISSUE TITLE
Custom previewTemplate

### ISSUE THREAD

**Issue by santo74** [FutoRicky/ember-cli-dropzonejs#45]
Dropzone has the ability to specify a previewTemplate parameter ([http://www.dropzonejs.com/#config-previewTemplate](http://www.dropzonejs.com/#config-previewTemplate)) which allows to use a custom template for image previews, but it seems this is currently not supported in this addon.

Could you please add this option to the addon?

**Comment by dustyjewett** [comment]
It's supported, just pass 
`previewTemplate:"<div>Template Html Goes Here</div>"`

**Comment by santo74** [comment]
Actually, what I meant to say is that I couldn't get it working.
I tried to define the property `previewTemplate="<div>code here</div>"` inside the component call, but it didn't do anything.
Anyway, in the meantime I'm not using any previewTemplate at all anymore.

**Comment by ghost** [comment]
I'm facing the same problem. Even though i defined a previewTemplate dzone is showing the default preview.
