### ISSUE TITLE
Initial Installation Fails

### ISSUE THREAD

**Issue by ghost** [FutoRicky/ember-cli-dropzonejs#58]
Either the guides are not complete or this breaks with Ember-Cli v2.10.

Error:
```console
Uncaught Error: Compile Error: drop-zone is not a helper
```

Template:
```hbs
{{drop-zone url='/endpoint'}}
```

**Comment by FutoRicky** [comment]
@mpash Have you tried with the latest version?

**Comment by FutoRicky** [comment]
Feel free to open if issue persists
