### ISSUE TITLE
What's the best way of changing the URL before the upload starts

### ISSUE THREAD

**Issue by wayne-o** [FutoRicky/ember-cli-dropzonejs#60]
I have the following in my component:

```
export default Ember.Component.extend({
	method: null,
	headers: null,
	token: null,
	fileName: null,
	url: Ember.computed('token', 'fileName', function () {
		let baseUrl = 'https://12345.blob.core.windows.net/ocr/';
		let filename = this.get('fileName');
		let token = this.get('token');
		return baseUrl + filename + token;
	}),
	addedFileEvent: Ember.computed(function () {
		var _this = this;
		return function (file) {
			_this.set('fileName', file.name);
		};
	})
});
```

And this in my template:

`{{drop-zone url=url method=method headers=headers addedfile=addedFileEvent }}`

But the `url`  computed property never fires.

What is the best way of modifying the URL each time a file is added and before it uploads to the server?

**Comment by FutoRicky** [comment]
For each time a file is added you can use the `addedFileEvent` computed function and set the `url` property directly from there. `_this.set('url', yourNewURL)`. There is a [`sending`](http://www.dropzonejs.com/#event-sending) event that you can use to do any process before each file is sent.

**Comment by wayne-o** [comment]
That's actually exactly what I tried but it doesn't seem to take the
updated value.

I suspect it's a race condition

**Comment by FutoRicky** [comment]
If you are referring to the original post's example, that is not being done there.

**Comment by wayne-o** [comment]
I have this in my controller:
```
		addedFileEventHandler: Ember.computed(function () {
			var _this = this;
			return function (file) {
				let token = _this.get('token');
				let pattern = `https://someblob.blob.core.windows.net/ocr/${file.name}${token}`;
				_this.set('url', pattern);
			};
		})
```

And this in my template:

` {{drop-zone url=url method=method headers=headers addedfile=addedFileEventHandler}}`

No dice. URL never changes inside the drop-zone component.

I have even added a computed property to drop-zone.js that watches `url` and it never fires. I have also tried `url=(mut url)` no dice.

**Comment by Name-less** [comment]
Did you finally find a workaround to change the url before the upload ?

I succeed by changing manually the url : 
` this.get('dropzone').options.url = MY_URL;`

And I can access my dropzone grace to this post :  https://github.com/FutoRicky/ember-cli-dropzonejs/issues/26
