### ISSUE TITLE
Dynamic Options Hash

### ISSUE THREAD

**Issue by donaldwasserman** [FutoRicky/ember-cli-dropzonejs#74]
Hey There - 

Would you be willing to consider a PR that introduces a more dynamic options hash? 

The current api to type out all the options is a little cumbersome for my (admittedly a little bit of an edge) use case. I need to pass in quite a bit of context-specific data into the component. 

I was thinking of an API somewhat like this: 

```hbs 
{{!-- my component --}}

{{drop-zone options=dynamic}}
```

and in my my-component.js
```js
options: {
endpoint: '/foo',
}
```

Let me know and I'll submit the PR

**Comment by FutoRicky** [comment]
Hey, make the PR so I can check it out. But it sounds like a reasonable update.

**Comment by FutoRicky** [comment]
https://github.com/FutoRicky/ember-cli-dropzonejs/pull/75
