### ISSUE TITLE
Use new fastboot guard

### ISSUE THREAD

**Issue by jakeleboeuf** [FutoRicky/ember-cli-dropzonejs#76]
> process.env.EMBER_CLI_FASTBOOT is soon going to be deprecated and [eventually removed](https://github.com/ember-fastboot/ember-cli-fastboot/issues/360). Therefore, we should instead use updateFastBootManifest hook.

https://github.com/ember-fastboot/ember-cli-fastboot#loading-additional-assets-in-fastboot-environment

**Comment by kratiahuja** [comment]
Hey @jakeleboeuf `updateFastBootManifest` should only be used for vendor files that you are importing in fastboot build. In your addon, you are only importing for browser build, therefore you should follow the guide here: https://gist.github.com/kratiahuja/d22de0fb1660cf0ef58f07a6bcbf1a1c#using-processenvember_cli_fastboot-to-run-import-in-browser-build

Another addon example: https://github.com/stefanpenner/ember-fetch/pull/29/files

Ping me on ember slack if you need help!

**Comment by jakeleboeuf** [comment]
Thanks for the explanation @kratiahuja! Maybe I'm a dumb-dumb (I am), but those examples seem to suggest what I'm doing here is overly complex... Is there a simpler way to rewrite [this?](https://gist.github.com/jakeleboeuf/4c7614b02a6bad00eb7395ca1b848c00)

**Comment by kratiahuja** [comment]
I think if you write the funnel trees in variables, it becomes more readable :) .

**Comment by FutoRicky** [comment]
Should be fixed by this commit https://github.com/FutoRicky/ember-cli-dropzonejs/commit/d9355e31e6ca4ca4a4f0a78f64d14dcfaa1a0b5c
