### ISSUE TITLE
Option `includeDropzoneCss` is not implemented

### ISSUE THREAD

**Issue by panthony** [FutoRicky/ember-cli-dropzonejs#86]
The option `includeDropzoneCss` described in the README.md file is not implemented.

Is the feature actually missing? Or it's the README file that is not up to date?

Also, thanks for this addon !

**Comment by FutoRicky** [comment]
Ahh thanks for pointing this out. Looks like I accidentally removed the feature when upgrading the ember version. I'll add it back again as soon as I get a chance. 👍

**Comment by FutoRicky** [comment]
Re-implemented feature 52498120132123c8f1497a235d2b1530a2cdf88f
