### ISSUE TITLE
includeDropzoneCss:false is not working

### ISSUE THREAD

**Issue by Khaled-M-Mansour** [FutoRicky/ember-cli-dropzonejs#88]
I added includeDropzoneCss:false to ember-cli-build.js but that didn't work, I can see dropzone css added to the vendor.css.
I think "included" hook gets triggered before the app options are set. 
The issue was resolved for me when I changed the "included" hook to the below:

```
included(app) {
    let options = app.options.emberCliDropzonejs || { includeDropzoneCss: true };

    this.import('vendor/dropzone.min.js');



    if (options.includeDropzoneCss){
      this.import('app/styles/dropzone.min.css');
    }
  }
```

**Comment by FutoRicky** [comment]
Thanks, nice catch. Will be updating soon.

**Comment by FutoRicky** [comment]
Updated `index.js`.

b73ae36bedf6916f548dfb0ce715cfb8dbdc8e04
