### ISSUE TITLE
Uncaught Error: Assertion Failed: A helper named 'drop-zone' could not be found

### ISSUE THREAD

**Issue by Kilowhisky** [FutoRicky/ember-cli-dropzonejs#9]
Trying to use this plugin i get

```
Uncaught Error: Assertion Failed: A helper named 'drop-zone' could not be found
```

package.json

```
"ember-cli-dropzonejs": "0.2.4",
```

ember app info

```
ember.debug.js:5378 DEBUG: -------------------------------
ember.debug.js:5378 DEBUG: Ember                     : 1.13.7
ember.debug.js:5378 DEBUG: Ember Data                : 1.13.9
ember.debug.js:5378 DEBUG: jQuery                    : 2.1.4
ember.debug.js:5378 DEBUG: Ember Simple Auth         : 0.8.0
ember.debug.js:5378 DEBUG: Ember Simple Auth Testing : 0.8.0
ember.debug.js:5378 DEBUG: -------------------------------
```

its appearing in vendor.js as this

```
define('ember-cli-dropzonejs/components/drop-zone/component', ['exports', 'ember'], function (exports, Ember) {
```

Any ideas?

**Comment by FutoRicky** [comment]
Did you do `bower install dropzone` ?

**Comment by jackmatt2** [comment]
@FutoRicky This is an issue when consumed from another addon also.  For example, I have an addon called boilerplate with ember-cli-dropzone installed.  I had to shim drop-zone to get it working in consuming projects.

``` javascript
//app/components/drop-zone.js
export { default } from 'ember-cli-dropzonejs/components/drop-zone/component';
```

I am pretty sure the solution is to rename `components/drop-zone/component.js` to `components/drop-zone.js` and it will work in all cases.   There is something about the pod structure that some consuming application don't like.  This is probably and ember-cli bug.

**Comment by bj-mcduck** [comment]
Getting this as well. Was wondering if I missed an `app.import`, but I don't see that mentioned in the docs.

**Comment by bj-mcduck** [comment]
@jackmatt2 using your shim fixes it for me. Thank you, a good temporary workaround!

**Comment by rafmst** [comment]
Hi, I'm getting this error to.
I'm new to ember so probably I'm missing something(my ember-cli version is 2.4.3).

First I run: 

```
sudo npm install ember-cli-dropzonejs
```

and then: 

```
bower install dropzone
```

I tried to insert the component normally using:

``` html
{{drop-zone url='http://example.com/example'}}
```

but I got the same error, saying drop-zone helper could not be found.
Thanks

**Comment by FutoRicky** [comment]
@ptraceur Do not install it with `sudo npm`, do `ember install ember-cli-dropzonejs` as the readme states.
