### ISSUE TITLE
Missing `renameFile` function

### ISSUE THREAD

**Issue by deivinsontejeda** [FutoRicky/ember-cli-dropzonejs#90]
Dropzone.js support [renameFile](http://www.dropzonejs.com/#config-renameFile) which is not added on this project. The change is very easy.

I'm using version 0.8.6 and it's not present and checking the latest (1.0.1) version I see that it's not present either

**Comment by deivinsontejeda** [comment]
I have created a branch in order to fix version 0.8.6 

https://github.com/deivinsontejeda/ember-cli-dropzonejs/tree/fix/add-missing-function-renamefile

**Comment by FutoRicky** [comment]
Thanks! Could not merge your branch because it was an old version.

**Comment by deivinsontejeda** [comment]
Yes, How we can create a new version from 0.8.6 and another from last one?

**Comment by FutoRicky** [comment]
Just fork the latest version
