### ISSUE TITLE
Uncaught Error: No URL provided.

### ISSUE THREAD

**Issue by Windvis** [FutoRicky/ember-cli-dropzonejs#94]
This exception is thrown (even though everything works).

This happens even with the most basic code:
`{{drop-zone url="/"}}`

I'm guessing this is related to: https://github.com/enyo/dropzone/issues/1355

**Comment by Windvis** [comment]
It looks like the autodiscover did its work before this line was executed. The exception is gone when I copy it to the root of the file, in the module scope. As I'm fairly new to Ember, I'm not sure where this kind of config should be added in the codebase, otherwise, I could make the PR.

https://github.com/FutoRicky/ember-cli-dropzonejs/blob/85db18b20868f285c43275d9c457f6863140746d/addon/components/drop-zone.js#L211

**Comment by FutoRicky** [comment]
Hi @NindroidX, sorry for the late response, I've been busy. Anyway, I would love to help out but I need more context on this issue. Is there a way I could recreate this issue, I'm currently unable to recreate it.

**Comment by Windvis** [comment]
Hey! No problem :D.

It seems like a fastboot problem. When I disable fastboot with `&fastboot=false` the error does not appear. I assume it's because fastboot renders the html structure on the server, and Dropzone tries to initialise it because it contains the default `.dropzone` class.

**Comment by FutoRicky** [comment]
What ember-cli version are you using?

**Comment by FutoRicky** [comment]
Closed due to inactivity

**Comment by oskarrough** [comment]
I'm also seeing this error and can confirm it goes away if you disable fastboot. Using ember-cli 3.4.3 + ember-cli-fastboot 2.0.0.

```
dropzone.min.js:1 Uncaught Error: No URL provided.
    at new b (dropzone.min.js:1)
    at dropzone.min.js:1
    at Function.Dropzone.discover (dropzone.min.js:1)
    at Dropzone._autoDiscoverFunction (dropzone.min.js:1)
    at HTMLDocument.d (dropzone.min.js:1)
```

I'm wondering if Dropzone should run at all in fastboot?

**Comment by catz** [comment]
run into the same issue with fastboot

wrapped in
`
{{#unless isFastBoot}}
   ...
`
