### ISSUE TITLE
Fails to build with Dropzone 5.5.0

### ISSUE THREAD

**Issue by ntodd** [FutoRicky/ember-cli-dropzonejs#95]
Dropzone JS 5.5.0 was packaged incorrectly and is missing the dist js files. See https://gitlab.com/meno/dropzone/issues/115 for issue.

Currently, installing ember-cli-dropzone will use dropzone 5.5.0 and therefore fails to build. This can be resolved by specifying dropzone version 5.4.0 in your project's `package.json` dependencies. Not sure if you want to lock the addon's package.json to 5.4.0 until a new version of dropzone is packaged, but figured I'd file an issue so people were aware.

**Comment by FutoRicky** [comment]
Thanks for the find. Updated the project https://github.com/FutoRicky/ember-cli-dropzonejs/pull/96
