### ISSUE TITLE
How to trigger reset event ?

### ISSUE THREAD

**Issue by blackode** [FutoRicky/ember-cli-dropzonejs#97]
## How I used?
I used this inside the form. 
```html
  <form>
   {{dropzone event1=(action 'actionName') }}
 </form>
```
## Problem or Requirement
I don't know how to trigger the `reset` event. I am supposed to reset the elements in the form to their 
initial status.
I did not find anything related inside the docs.

**Comment by FutoRicky** [comment]
Hi, sorry for the late response. Are you still having this issue?

**Comment by FutoRicky** [comment]
Closed due to inactivity
